---
channel: stable
addons:
  plex:
    repository: lbouriez/addon-plex
    target: plex
    image: ghcr.io/lbouriez/addon-plex/{arch}
  ttrss:
    repository: lbouriez/addon-tt-rss
    target: ttrss
    image: ghcr.io/lbouriez/addon-tt-rss/{arch}
  sonarr:
    repository: lbouriez/addon-sonarr
    target: sonarr
    image: ghcr.io/lbouriez/addon-sonarr/{arch}