---
channel: stable
addons:
  plex:
    repository: lbouriez/addon-plex
    target: plex
    image: ghcr.io/lbouriez/addon-plex/{arch}
  ttrss:
    repository: lbouriez/addon-tt-rss
    target: ttrss
    image: ghcr.io/lbouriez/addon-tt-rss/{arch}
  sonarr:
    repository: lbouriez/addon-sonarr
    target: sonarr
    image: ghcr.io/lbouriez/addon-sonarr/{arch}
  jackett:
    repository: lbouriez/addon-jackett
    target: jackett
    image: ghcr.io/lbouriez/addon-jackett/{arch}
  radarr:
    repository: lbouriez/addon-radarr
    target: radarr
    image: ghcr.io/lbouriez/addon-radarr/{arch}
  inadyn:
    repository: lbouriez/addon-inadyn
    target: inadyn
    image: ghcr.io/lbouriez/addon-inadyn/{arch}
  whoogle-search:
    repository: lbouriez/addon-whoogle-search
    target: whoogle-search
    image: ghcr.io/lbouriez/addon-whoogle-search/{arch}
