arch:
- aarch64
- amd64
- armv7
description: Inadyn is a small and simple Dynamic DNS, DDNS, client with HTTPS support
image: ghcr.io/lbouriez/addon-inadyn/{arch}
map:
- ssl
name: Inadyn
options:
  providers:
  - hostname: dynamic-subdomain.example.com
    password: password
    provider: yourprovider
    username: username
schema:
  allow_ipv6: bool?
  fake_address: bool?
  forced_update: int?
  iface: str?
  iterations: int?
  period: int?
  providers:
  - provider: str
    custom_provider: bool?
    username: str
    password: str?
    ssl: bool?
    hostname: str
    checkip_ssl: bool?
    checkip_server: str?
    checkip_command: str?
    checkip_path: str?
    user_agent: str?
    wildcard: bool?
    ddns_server: str?
    ddns_path: str?
    append_myip: bool?
    proxied: bool?
    ttl: int?
  secure_ssl: bool?
  verify_address: bool?
slug: inadyn
url: https://github.com/lbouriez/addon-inadyn
version: 2.9.2
